FROM node:14-alpine
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json .
COPY decorate-angular-cli.js .

RUN npm install --legacy-peer-deps
RUN npm install pm2 -g

COPY . .

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 3000
RUN npm run build:api:docker
CMD pm2-runtime ./dist/apps/api/main.js
