FROM node:14-alpine
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json .
COPY decorate-angular-cli.js .

RUN npm install --legacy-peer-deps
RUN npm install pm2 -g

# Copy app source code
COPY . .

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 4000
RUN npm run build:site:docker
CMD pm2-runtime ./dist/site/server/main.js
