FROM node:latest
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json .

RUN npm install
RUN npm install -g nx
RUN npm install pm2 -g

COPY . .

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 3000
RUN nx run api:build
CMD pm2-runtime ./dist/apps/api/main.js
