FROM node:latest
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package*.json ./

RUN npm install
RUN npm install pm2@latest -g
RUN npm install nx -g
RUN pm2 update

# Copy app source code
COPY . .

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 4000
RUN npm run build:ssr
RUN npm run prerender
CMD pm2-runtime ./dist/site/server/main.js
