// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/common/Buttons/AppButton/AppButton.vue')['default']
    AppContainer: typeof import('./components/layout/AppContainer/AppContainer.vue')['default']
    AppHeader: typeof import('./components/global/AppHeader/AppHeader.vue')['default']
    AppNavigation: typeof import('./components/global/AppNavigation/AppNavigation.vue')['default']
    AppNavigationLink: typeof import('./components/global/AppNavigation/AppNavigationLink/AppNavigationLink.vue')['default']
    ButtonLink: typeof import('./components/common/Buttons/ButtonLink/ButtonLink.vue')['default']
    Card: typeof import('./components/layout/Card/Card.vue')['default']
    Container: typeof import('./components/layout/Container/Container.vue')['default']
    Flex: typeof import('./components/layout/Flex/Flex.vue')['default']
    FlexItem: typeof import('./components/layout/FlexItem/FlexItem.vue')['default']
    RbIconButton: typeof import('./components/common/Buttons/RbIconButton/RbIconButton.vue')['default']
    RbLink: typeof import('./components/common/RbLink/RbLink.vue')['default']
    RbModal: typeof import('./components/common/RbModal/RbModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./components/form/TextInput/TextInput.vue')['default']
    UnderConstruction: typeof import('./components/common/UnderConstruction/UnderConstruction.vue')['default']
  }
}
