// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RbButton: typeof import('./components/common/Buttons/RbButton/RbButton.vue')['default']
    RbButtonLink: typeof import('./components/common/Buttons/RbButtonLink/RbButtonLink.vue')['default']
    RbCard: typeof import('./components/layout/RbCard/RbCard.vue')['default']
    RbContainer: typeof import('./components/layout/RbContainer/RbContainer.vue')['default']
    RbFlex: typeof import('./components/layout/RbFlex/RbFlex.vue')['default']
    RbFlexItem: typeof import('./components/layout/RbFlexItem/RbFlexItem.vue')['default']
    RbHeader: typeof import('./components/global/RbHeader/RbHeader.vue')['default']
    RbIconButton: typeof import('./components/common/Buttons/RbIconButton/RbIconButton.vue')['default']
    RbLink: typeof import('./components/common/RbLink/RbLink.vue')['default']
    RbModal: typeof import('./components/common/RbModal/RbModal.vue')['default']
    RbNavigation: typeof import('./components/global/RbNavigation/RbNavigation.vue')['default']
    RbNavigationLink: typeof import('./components/global/RbNavigation/RbNavigationLink/RbNavigationLink.vue')['default']
    RbPageLoader: typeof import('./components/common/RbPageLoader/RbPageLoader.vue')['default']
    RbPill: typeof import('./components/common/RbPill/RbPill.vue')['default']
    RbTechLogo: typeof import('./components/common/RbTechLogo/RbTechLogo.vue')['default']
    RbTextInput: typeof import('./components/form/RbTextInput/RbTextInput.vue')['default']
    RbUnderConstruction: typeof import('./components/common/RbUnderConstruction/RbUnderConstruction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
