// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContainer: typeof import('./components/layout/AppContainer/AppContainer.vue')['default']
    AppHeader: typeof import('./components/global/AppHeader/AppHeader.vue')['default']
    AppNavigation: typeof import('./components/global/AppNavigation/AppNavigation.vue')['default']
    AppNavigationLink: typeof import('./components/global/AppNavigation/AppNavigationLink/AppNavigationLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
  }
}
