CREATE TABLE blog (Id SERIAL PRIMARY KEY, Title VARCHAR(255) NOT NULL, Content VARCHAR(65536) NOT NULL, DateAdded TIMESTAMP NOT NULL, DateModified TIMESTAMP NOT NULL);

CREATE TABLE AiImages (Id SERIAL PRIMARY KEY, PATH VARCHAR(510) NOT NULL, DateAdded TIMESTAMP NOT NULL, ExpiryTime TIMESTAMP NOT NULL);

CREATE TABLE Tasks (Id SERIAL PRIMARY KEY, Title VARCHAR(255) NOT NULL, Completed BOOLEAN NOT NULL DEFAULT FALSE, DateAdded TIMESTAMP NOT NULL, DateModified TIMESTAMP NOT NULL);
