name: Build & Test Go API

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Generate Mocks
        shell: bash
        run: ./generateMocks.sh

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...